name: Deploy staging-function

on:
  pull_request:
    types: [ready_for_review, opened, reopened, synchronize]
    branches:
      - main

jobs:
  build-and-deploy-staging:
    name: Call reusable workflow when pull request is created
    if: github.event.pull_request.draft == false
    uses: Informasjonsforvaltning/workflows/.github/workflows/deploy-cloud-function.yaml@main
    with:
      app_name: user-feedback-service-staging
      entry_point: EntryPoint
      environment: staging
      go-version: 1.21.4
      go-test-cmd: '-v ./...'
      max_instances: 1
      memory: 256
      region: europe-west1
      runtime: go121
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DIGDIR_CLOUD_FUNCTIONS_SA_KEY: ${{ secrets.DIGDIR_CLOUD_FUNCTIONS_SA_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      ENV_VARS: ${{ secrets.ENV_VARS_STAGING }}
