name: Deploy prod-function

on:
  push:
    branches:
      -  main

jobs:
  build-and-deploy-production:
    name: Deploy to prod on merge to main branch
    uses: Informasjonsforvaltning/workflows/.github/workflows/deploy-cloud-function.yaml@main
    with:
      app_name: user-feedback-service-prod
      entry_point: EntryPoint
      environment: prod
      go-version: 1.24.1
      go-test-cmd: '-v ./...'
      max_instances: 1
      memory: 256
      region: europe-west1
      runtime: go122
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DIGDIR_CLOUD_FUNCTIONS_SA_KEY: ${{ secrets.DIGDIR_CLOUD_FUNCTIONS_SA_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      ENV_VARS: ${{ secrets.ENV_VARS }}
